/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'egaozhi' at '6/29/16 4:25 PM' with Gradle 2.14
 *
 * @author egaozhi, @date 6/29/16 4:25 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
